name: Matrix
on: push 

jobs:
  node_version:
    runs-on: ubuntu-latest
    steps:
      - name: log node version
        run: node -v 
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: log node version
        run: node -v 